[package]
name = "manifolds"
version = "0.1.0"
authors = ["Mike"]
edition = "2018"

[dependencies]
ash = "0.29.0"
winit = "0.20.0-alpha4"
winapi = { version = "0.3.5", features = ["windef", "libloaderapi"] }
slice-of-array = "0.2"
nalgebra = "0.19.0"
nalgebra-glm = "0.5.0"